[package]
name = "loki_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.23", features = ["json"] }
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"] }
loki-api = "0.1.1"
snap = "1.1.1"
chrono = "0.4.31"
serde = { version = "1.0.195", features = ["derive"]}
serde_json = "1.0.111"

color-eyre = { version = "0.5", default-features = false }